services:
  app:
    build:
      context: images/node
    container_name: app
    entrypoint: sh -c "npm install && npm start"
    volumes:
      - ./app:/usr/src/app
    networks:
      - node-network
    depends_on:
      db:
        condition: service_healthy
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-network
    depends_on:
      - app

  db:
    image: mysql:8.0.32
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_ROOT_PASSWORD=fullcycle
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - node-network

networks:
  node-network:
    driver: bridge